# Generated by Django 5.0.3 on 2024-04-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='houseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('square_feet', models.IntegerField()),
                ('no_of_bedrooms', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='houseListingModel',
        ),
    ]
